# Goal-setting

Our purpose today is to set some goals for yourself that you can act on this summer

## What would you like to revisit from your values and workflow last week? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.1--->

*What drives you? Who are your allies, colleagues, and mentors that give you energy and support?*

Allies, Colleagues and mentors that give me energy
Julie L
Katie K
Steve C
(hoping Lauran B)
Michelle M
Scott L
Sarah G
Bill M, Mike G
NCCR folks

my team:
Megan W
Angelia M

Drives me: Doing good work that matters

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## What goals are emerging for your workflow?

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.2--->

*Dream big. Why are you committed to these goals?*

  
Reengaging with workflow discussion
Get more ppl excited about doing things together
Cutting time worrying about others, but not diminishing the support I'm giving them
 
You said small things, but I want to do great things (aka Walkup song!)
 
BRinging more of my workflow into all of my courses
 
 

 

  

  

 

  

  

 

:::


## What pieces do you have control over in the short and long term? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.2--->

*What are the possibilities? And what are the barriers? What questions do you need answered, what conversations do you need to have?*

Short term:
Scope of Concept paper
Possibilities - way of getting a bunch of great people together to have good conversations to generate momentum for more equitable blue economy development for the south coast.
Barriers - budget constraints (can't do all the things in one thing)
Conversation - ask for higher budget

Long term:
Hiring, Clearer expectations 
More recognition of energy  

 


:::

## What actions can you take this summer in service of these bigger goals?

::: {.callout-tip appearance="minimal" icon="false"}


<!---p.3--->

*What would you like to experiment with? Where is a place you could try something new? For example - if I feel behind every morning, what would it look like to not set meetings before 10am?*

Fewer meetings with student but with clearer definition of what I want to see.
More shared understanding - maybe ask at a lab meeting for everyone to share how they communicate their work.

Revisions to lab manual

Short news posts on website to communicate about what is happening in the group

Not adding anything more to my schedule

 


:::

## What would success look like? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.3--->

*What feedback would you need from yourself to know if your actions/ experiment is working or needs to be iterated? How can you give yourself grace?*

Recognize that it isn't all me (in terms of student success)

Did I make time to paint miniatures / go kayaking / play wingspan, etc.
  
Have I made progress toward the larger COP goal this week?
 

:::



## What do you need to make this possible? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.4--->

*What support or accountability could help you? For example, journaling or sharing progress with a colleague for a set period of time*

Like the idea of a journal entry on differnet goals
Training (SIGE and OMMOWW, CINAR, )
Coastal Resilience Partnerships at UMassD

Sharing progress with colleagues outside of the project team

Setting time for writing, that can also be for sharing
  

 

 

:::


## What’s something you’re excited about that you could share with others? 

::: {.callout-tip appearance="minimal" icon="false"}

<!---p.5--->

Three students from my lab are participating in Commencement tomorrow! And Angelia is joinging the New England Council and taking all this reproducible open science mindset with her. So excited.

 
 

:::
