# Reimagine

Our purpose today is to spot things that could help your workflow. The ideas is to reuse what works (for you and others), and ease off what doesn’t work


## What resonates for you from last week?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.1--->

*Revisit what was top-of-mind from last week. What else has emerged? What patterns, if any, are coming up for you?*

Top of mind was ideating around a UMassD community of practice on coastal sustainability
Since then, an internal call for concept papers around Blue Economy has been issued.
Thinking lots about how to translate work we are doing and thinking about doing to make this opportunity what it can be given the limited budget constraints. 

Pattern - thinking about how to support students so they can be successful with both skills acquisition and domain understanding, in timely fashion, and to make our time together more efficient. Provide scaffold for their communication about the work to minimize both our times. (eg, how can I help them to help me help them)

Talked last week about recognizing that I enjoy when I am contributing to things in a way that I know they will be reused. 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
:::

## Where within your workflow seems like a good place to start iterating?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What stands out about that place? Why are you motivated to focus on this part of your workflow?*

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::


## Think of a good workflow you’ve seen. What felt good about it? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*For example, what was it about how it was organized, how different people contributed, how it was communicated? Remember meetings are part of workflows too*

Meetings are on my mind a lot.

I think about projects like our Data-limited Research Track WG, and the State-space RTWG.

DLRTWG, good buy in from WG members to do work in between meetings and bring and share that work to our meetings

SSRTWG, project lead v. comfortable cancelling meetings if no progress to report from members 

SSRTWG - OK reimagining role because of other commitments, shifted to more reviewer. This was OK because there were others who were able to take on the leadership roles I needed to step out of.

Also think about the proposal writing meeting Eli and Julie and I had for our recent WFC session. Very focused, very productive and efficient. 

 

 

 
 

 

  

  

 

  

  

 


:::

## What have you seen or heard about that has you curious? 

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.2--->

*What are things you’d like to learn or reuse from what you’ve seen? Think from colleagues, talks, and examples online*

NASA Openscapes. All of it.  

Space creation for ideating in a community of practice. SFI model, Community Building from Home, etc.



  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 


:::

## What are some of your values?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.3--->

*Think about something you enjoy doing. What qualities about yourself do you see coming through? What is important to you personally and professionally? How do you want to make people feel?*

Playing Board Games with others.
- Enthusiasm for Sandbox Problem solving
- Teamwork, collaboration

Working with other people
Helping others do the work that is important to them.
Doing good work that matters.  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::

## How do your values show up in your workflow, and how you interact with colleagues?

::: {.callout-caution appearance="minimal" icon="false"}


<!---p.3--->

*How do you show up in your daily life at work? For example, being on time, being organized, interacting with people.*

Amplify work of others (share successes)
(Over)-work to help students
Prepare for meetings
 

 
 

 

  

  

 

  

  

 

 

  

  

 
:::


## What would it look like to connect your values more with your workflow?

::: {.callout-caution appearance="minimal" icon="false"}

<!---p.4--->

*Think about that place that seems like a good place to focus. What if you brought what you have seen and want to learn to that place, along with your values? You can draw this*

  
Give more time to long work.
Do fewer things.

Think about Blue economy proposal. How can I write this so it synergizes scholarship, training, and community building (on and off campus). Be OK with linking it to ongoing things, ask for more $ than the cap to hire a program coordinator (or envisage a student role for this).
  

 

  

  

 

  
  
 

 

 
 

 

  

  

 

  

  

 

 

  

  

 

  

 

 

 
 

 

  

  

 

  

  

 

:::
